spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    console: "%d{\"yyyy-MM-dd'T'HH:mm:ss.SSSZ\"} %highlight(%-5level) [%21thread] %cyan(%logger{25}.%M:%line) %msg%n"
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    org.hibernate: WARN
    org.hibernate.SQL: DEBUG
    jdbc.resultsettable: DEBUG
    jdbc.sqltiming: DEBUG

